# App metadata; see https://appfair.net/#App.yml
app:
  #name: "App Name" # 30-char limit
  #subtitle: "A brief summary of the App" # 30-char limit
  #keywords: "appfair,free" # comma separated keywords ; 100-char limit
  #description: "A complete description of the app" # 4000-char limit
  #notes: "Some notes about this app for reviewers."

  # primary_category and secondary_category can be any of: FOOD_AND_DRINK, BUSINESS, EDUCATION, SOCIAL_NETWORKING, BOOKS, SPORTS, FINANCE, REFERENCE, GRAPHICS_AND_DESIGN, DEVELOPER_TOOLS, HEALTH_AND_FITNESS, MUSIC, WEATHER, TRAVEL, ENTERTAINMENT, STICKERS, GAMES, LIFESTYLE, MEDICAL, MAGAZINES_AND_NEWSPAPERS, UTILITIES, SHOPPING, PRODUCTIVITY, NEWS, PHOTO_AND_VIDEO, NAVIGATION

  primary_category: "UTILITIES" 
  secondary_category: "PRODUCTIVITY"


  # translations for the name, subtitle, description, and keywords
  # Supported language keys are: # ar-SA, ca, cs, da, de-DE, el, en-AU, en-CA, en-GB, en-US, es-ES, es-MX, fi, fr-CA, fr-FR, he, hi, hr, hu, id, it, ja, ko, ms, nl-NL, no, pl, pt-BR, pt-PT, ro, ru, sk, sv, th, tr, uk, vi, zh-Hans, zh-Hant

  localizations:
    #fr-FR:
    #  name: "App Name in French"
    #  subtitle: "App Subtitle in French"
    #  description: "App Description in French"

# marketplace-issued indentifiers for the distribution channels for this app
markets:
  testflight: '1639901758'    # the assigned TestFlight id
  testflighturl: "https://testflight.apple.com/join/FoDQpXch"  # the public TestFlight beta link
  #appstore: '0123456789'      # the assigned App Store id
  #appstoreurl: "https://…"    # the official App Store landing page
  #playstore: '123456543210'   # the assigned Play Store id

# Pages / Jekyll configuration:
remote_theme: "appfair/fairapp-theme"

# the app icon is generated from a simple SVG path and a tint color
icon:
  # gradient tint color (symbolic name or "#RRGGBB")
  tint: "red"
  # SVG path to place in the center of the icon
  path: "M0 200 v-200 h200 a100,100 90 0,1 0,200 a100,100 90 0,1 -200,0 z"


