name: "Create Release"
# Create Release is invoked manually to build and distribute
# a new release to the App Fair.
#
# See: https://www.appfair.net
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Semantic Version'
        required: true

jobs:
  call-workflow:
    uses: fair-ground/Fair/.github/workflows/fork_apply.yml@main
    with:
      fairground: appfair
      release_version: "${{ github.event.inputs.version }}"
      target_macos: true
      target_linux: false
      target_windows: false
      target_ios: true
      target_tvos: false
      target_watchos: false
    secrets:
      # Optional notarization secrets that can be configured in the fork's organization
      NOTARY_TEAMID: ${{ secrets.NOTARY_TEAMID }}
      NOTARY_USERID: ${{ secrets.NOTARY_USERID }}
      NOTARY_PASSWORD: ${{ secrets.NOTARY_PASSWORD }}
      NOTARY_CERTKEY_P12_BASE64: ${{ secrets.NOTARY_CERTKEY_P12_BASE64 }}
      NOTARY_CERTKEY_PASSWORD: ${{ secrets.NOTARY_CERTKEY_PASSWORD }}
