name: "Fork Apply"
# Fork Apply runs in the forked repo with any push to main or semver tag
on:
  push:
    branches: [ main ]
    tags: "[0-9]+.[0-9]+.[0-9]+"

jobs:
  call-workflow:
    uses: fair-ground/Fair/.github/workflows/fork_apply.yml@main
    with:
      fairground: appfair
      target_macos: true
      target_linux: false
      target_windows: false
      target_ios: true
      target_tvos: false
      target_watchos: false

