name: "Integrate Release"
# Integrate release runs in the base repo when it receives a pull request
on:
  pull_request_target:
    branches: [ main ]
    types: [opened, reopened]

jobs:
  call-workflow:
    uses: fair-ground/Fair/.github/workflows/integrate_release.yml@main
    with:
      fairground: appfair
      fairseal_issuer: appfairbot
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      bot_token: ${{ secrets.APP_FAIR_BOT_TOKEN }}
      allow_name: ${{ secrets.APP_FAIR_ALLOW_NAME }}
      deny_name: ${{ secrets.APP_FAIR_DENY_NAME }}
      allow_from: ${{ secrets.APP_FAIR_ALLOW_FROM }}
      deny_from: ${{ secrets.APP_FAIR_DENY_FROM }}

