name: "Integrate Release"
# Integrate release runs in the base repo when it receives a pull request
on:
  pull_request_target:
    branches: [ main ]
    types: [opened, reopened]

jobs:
  call-workflow:
    uses: fair-ground/Fair/.github/workflows/integrate_release.yml@main
    secrets:
      token: ${{ secrets.TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      APP_FAIR_BOT_TOKEN: ${{ secrets.APP_FAIR_BOT_TOKEN }}
      APP_FAIR_ALLOW_NAME: ${{ secrets.APP_FAIR_ALLOW_NAME }}
      APP_FAIR_DENY_NAME: ${{ secrets.APP_FAIR_DENY_NAME }}
      APP_FAIR_ALLOW_FROM: ${{ secrets.APP_FAIR_ALLOW_FROM }}
      APP_FAIR_DENY_FROM: ${{ secrets.APP_FAIR_DENY_FROM }}

