name: "Integrate Release"
# Integrate release runs in the base repo
# when it receives a pull request
#
# This workflow only needs to be configured 
# by the base (upstream) fairground.
#
# See: https://www.appfair.net
on:
  pull_request_target:
    branches: [ main ]
    types: [opened, reopened]

jobs:
  call-workflow:
    uses: fair-ground/Fair/.github/workflows/fair.yml@main
    with:
      fairground: appfair
      target_macos: true
      target_linux: false
      target_windows: false
      target_ios: true
      target_tvos: false
      target_watchos: false
      fairseal_issuer: appfairbot
      license: AGPL-3.0
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      bot_token: ${{ secrets.APP_FAIR_BOT_TOKEN }}
      allow_name: ${{ secrets.APP_FAIR_ALLOW_NAME }}
      deny_name: ${{ secrets.APP_FAIR_DENY_NAME }}
      allow_from: ${{ secrets.APP_FAIR_ALLOW_FROM }}
      deny_from: ${{ secrets.APP_FAIR_DENY_FROM }}
      fairseal_key: ${{ secrets.APP_FAIR_FAIRSEAL_KEY }}


